table 'Order Details'
	lineageTag: a8b0ad7e-f6b5-4b73-a0e1-3e4b100f6a1a

	measure 執行加總 = RUNNINGSUM([m_SalesAmount],ORDERBY([FirstName],DESC))
		lineageTag: 32cfd016-4f9c-4cce-8193-7b8a4f0c28f4

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 34d8a42b-a374-4004-b6c2-f885ac07b58b
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: fac69e84-0f04-4464-af87-63f017a48678
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: "NT$"#,0.###############;-"NT$"#,0.###############;"NT$"#,0.###############
		lineageTag: dc9dd0db-8d61-4994-83c6-ea2952bbe48e
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"zh-TW"}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 874f6ce7-831a-4d37-9067-b9d53b6052e6
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: d341cca8-67b2-4492-8bfb-3c9620491f11
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Order Details' = m
		mode: import
		source =
				let
				    來源 = Sql.Database(".", "Northwind"),
				    #"dbo_Order Details" = 來源{[Schema="dbo",Item="Order Details"]}[Data]
				in
				    #"dbo_Order Details"

	annotation PBI_ResultType = Table

